server:
  management:
    endpoints:
      web:
        exposure:
          include: "health"
    endpoint:
      health:
        show-details: always
  port: 8080
  servlet:
    context-path: /dummyjson-client/api/1.1